### ISSUE TITLE
The plugin doesn't work

### ISSUE THREAD

**Issue by stillnaughty** [cxsper/vue-cli-plugin-sugarss#1]
```
<template>
  <div class="hello">
    <h1>testing</h1>
  </div>
</template>
<style scoped lang="sss">
h1
  background: green
</style>
```

A few spike here:
• Indeed specifying lang="sss" did parse the syntax following sugarss syntax.  Adding curling bracket will show error.  The parser should load correctly
• However, even the style is set correct, no style will be added to h1 element when rendering the page. (Try not setting scoped attributes also but also same result)

Is there something wrong on the plugin.  Or would you mind show an example on how to use the plugin. Thanks

**Comment by cxsper** [comment]
@stillnaughty so now you can go either with [lang=stylus] or with [lang=sass], reinstall the package please.

**Comment by cxspxr** [comment]
@stillnaughty from now on you can use [lang=sss] as you did if it matters for you. reinstall the package.

**Comment by cxspxr** [comment]
@stillnaughty let me know if it works for you

**Comment by stillnaughty** [comment]
Thanks.. prompt reply~!
Trying... so... quick question
1. specify either lang=stylus, lang=sass or lang=sss have the same result... or sass for sass format & sss for sugarss format (as they are a bit different in syntax)
2. is installation of sass-loader npm plugin mandatory?   If so, it may be better to include installing sass-loader npm when calling 'vue add sugarss'

Still trying...

**Comment by cxsper** [comment]
@stillnaughty okay let me explain this better in the readme. Yes, it is mandatory for your language of choice. SASS/Stylus.

**Comment by cxspxr** [comment]
@stillnaughty although it should not include any loaders because typically you use either SASS or Stylus not both. And your suggestion requires to include both loaders. Let me think about it.

**Comment by cxspxr** [comment]
@stillnaughty okay, it makes sense to include those loaders because SugarSS is only for SASS/Stylus. So it's okay to wire them as well. New version has been published to npm. No action required from you except reinstallation 

```bash
$ npm uninstall --save-dev vue-cli-plugin-sugarss
$ vue add sugarss
```

**Comment by cxspxr** [comment]
@stillnaughty oh, it should probably be in conflict now. Because both sass and stylus loaders will try to parse .sss and style[lang=sss]. Let me investigate this. That's another problem of including both loaders.

**Comment by stillnaughty** [comment]
no problem~ !
it's already good you make this library~
so... still not working right?
i'll be closely monitoring the situation adn thanks ;-)

**Comment by cxspxr** [comment]
@stillnaughty it should work now.

**BUT** basically now you can go with `style[lang=sss]` or `.sss` ***only***. **NOT** with `style[lang=sass]` nor `style[lang=stylus]`. You can, but in this case SugarSS won't work anymore.

So your very first example should work now (with a new version installed haha). At least it works for me with a clean `vue create` project.

**Comment by stillnaughty** [comment]
Cannot find module 'stylus-loader' >> should add this npm right?

**Comment by cxspxr** [comment]
@stillnaughty no, it's ridiculous mistake made by me

**Comment by cxspxr** [comment]
@stillnaughty I'm sorry for the amount of trials you did. I just haven't had no free time to look at it thoroughly. 
It was me requiring `sass` and `stylus` loaders since I was trying conditional loaders usage. And it has become redundant and produced an error after I configured `sugarss` parser properly.

Now it works.

**Comment by stillnaughty** [comment]
Finally~! awesome~~ ;-)
