### ISSUE TITLE
sugarss combined with postcss-nested & postcss-nested-props?

### ISSUE THREAD

**Issue by stillnaughty** [cxsper/vue-cli-plugin-sugarss#2]
Hi.. it's me again. :p
How can I use sugarss combined with postcss-nested & postcss-nested-props?

That's quite essential and could only make sugarss useful only if we can use write nested syntax imo.
Spend some hours but still can't make them work on sugarss in vue cli3.  Need some help from you here~

**Comment by cxspxr** [comment]
Please, provide your broken examples.

**Comment by stillnaughty** [comment]
```
npm install postcss-nested
npm install postcss-nested-props
```

Say a sample SSS is as below:
```
.foo
    &.test  // syntax supported by postcss-nested
        font // syntax supported by postcss-nested-props
            weight: bold      
            size: 12px
        margin
            top: 10px
            left: 10px
```

Probably it's owing to the confusion on how to set vue.config.js / package.json.
But I suspect postcss-nested & postcss-nested-props do work but just it's on .css file but not in .sss file.

Try goolge hard, having several ways to set on either package.json / vue.config.js but same result. sugarss is successfully loaded but not supporting postcss-nested & postcss-nested syntax.

Truly wish to have a working example how sugarss works with other postcss plugins or just

**Comment by cxspxr** [comment]
I will look into it. I've tried these plugins using `vue.config.js` as well and it was working perfectly

**Comment by stillnaughty** [comment]
sorry maybe i'm not quite used to vue cli3 at the moment
so ... mind to ask how to set postcss-nested & postcss-nested-props in vue.config.js?
I can't make these plugins gel together with sugarss

**Comment by cxspxr** [comment]
@stillnaughty I've got my motherboard broken yesterday.
I won't be able to look at it properly in quite some time. Could you please provide me with some examples of `vue.config.js` you tried so far so that I could see them at least? 

I personally used examples from `@vue/cli` and `postcss` docs in order to manage these plugins.

**Comment by stillnaughty** [comment]
Sure..

Here's what I've tried

1. package.json
```
  "vue": {
    ...
    "css": {
      "loaderOptions": {
        "postcss": { // <=== tried sugarss / sss as well, result in compile error
          "plugins": {
            "postcss-nested": {},
            "postcss-nested-props": {}
          }
        }
      }
    }
```
```
    ...
    "css": {
      "loaderOptions": {
        "postcss": { // <=== tried sugarss / sss as well, result in compile error
          "postcss-nested": {},
          "postcss-nested-props": {}
        }
      }
    }
  }
```
```
  "postcss": {
    "plugins": {
      "postcss-nested": {},
      "postcss-nested-props": {},
      "autoprefixer": {}
    }
  },
```

2. postcss.config.js

```
module.exports = {
  parser: "sugarss", // <=== tried postcss / sss as well, no effect
  plugins: {
    "postcss-nested": {},
    "postcss-nested-props": {}
  }
};
```

3. vue.config.js, clear vue properties in package.json as well
```
module.exports = {
  ...
  css: {
    loaderOptions: {
      postcss: { // <=== tried sugarss / sss as well, result in compile error
        plugins: {
          "postcss-nested": {},
          "postcss-nested-props": {}
        }
      }
    }
  }
};
```
```
 css: {
     modules: true,
     loaderOptions: {
      sss: { // <=== tried sugarss / sss as well, result in compile error
        plugins: [
          require("postcss-nested"),
          require("postcss-nested-props")
        ]
      }
    }
  }
```

**Comment by cxspxr** [comment]
first in **3** should work. Have you installed `postcss-nested` & `-props`?

**Comment by stillnaughty** [comment]
sure~
checked with package.json & package-lock.json and such npm packages have installed.
So... you managed to make these 3 al-together?
It isn't on my case indeed...

**Comment by stillnaughty** [comment]
Any hint on it? i really can't make it work these 3 plugins altogether

**Comment by cxspxr** [comment]
Have no free time, will try to investigate asap. Keep in touch

**Comment by cxspxr** [comment]
@stillnaughty hey, how do you think, should I add these plugins support here or should I create extended plugin version with those plugins? Because they're just ones of many.... idk. Btw, I got it working, just deciding where to put it.

**Comment by cxspxr** [comment]
@stillnaughty nvm, I found a smart way

**Comment by cxspxr** [comment]
@stillnaughty see [readme](https://github.com/cxsper/vue-cli-plugin-sugarss#postcss-plugins). Feel free to re-open on demand. Also don't forget to update the plugin by
```bash
$ npm uninstall -D vue-cli-plugin-sugarss
$ vue add sugarss
```

**P.S.** I just thought it would be bloating if I add support for nesting directly in my plugin. Because there are many plugins for `postcss` then why shouldn't I include them as well? And official `sugarss` doesn't include any plugins out of the box. So that being said, from now and on you can add any plugins you want. And actually you have been able to do it previously, I just made it more comfortable now.
